n1 = input ('Digite alguma coisa: ')
print (' Qual o tipo da classe?',type(n1))
print ('é um número?',n1.isnumeric())
print ('é alfabetico? ',n1.isalpha())
print  ('é alfanumérico?',n1.isalnum())
print ('está em maiúsculo?',n1.isupper())
print ('está capitalizada?',n1.istitle())
print ('só tem espaços?',n1.isspace())
print('está em minúsculo?',n1.islower())